### ISSUE TITLE
Is it possible to validate that _type is a yaml sequence?

### ISSUE THREAD

**Issue by psynaptic** [romaricdrigon/MetaYaml#11]
It would be highly yaml loader specific, so I'm not sure it belongs in core, but we have the need to validate that a structure is a yaml sequence. Is this possible, and if so, how would I generally go about it?

**Comment by romaricdrigon** [comment]
Hello,

To be sure, you want to check than some output is YAML, isn't it?
Do you have an example?

**Comment by psynaptic** [comment]
Thank you for the amazingly fast response!

I have a YAML document that has "sequences" in it, for example:

```yaml
foo:
  - ordered_element_1
  - ordered_element_2
  - ordered_element_3
      type: bar
      baz:
        - ordered_element_1
        - ordered_element_2
```

I think what these are as per the spec are "Ordered Mappings". They ensure the order of elements which is essential to parts of our schema.

Does this feature already exist or can I add it somehow, perhaps in user land code?

**Comment by romaricdrigon** [comment]
I'm not sure to totally get you yet. You want to validate that
ordered_element_1-2-3 are exactly, respectively, first, second and third
items? And not something else?

I don't have my computer here to try, I would try to put an "array" node -
those are afficheur arrays in PHP terms, an array with unordered elements
is an prototype in Metayaml - whose subelements are named 0, 1 and 2.

Le jeudi 29 octobre 2015, Richard Burford <notifications@github.com> a
écrit :

> Thank you for the amazingly fast response!
>
> I have a YAML document that has "sequences" in it, for example:
>
> foo:
>   - ordered_element_1
>   - ordered_element_2
>   - ordered_element_3
>       type: bar
>       baz:
>         - ordered_element_1
>         - ordered_element_2
>
> I think what these are as per the spec are "Ordered Mappings". They ensure
> the order of elements which is essential to parts of our schema.
>
> Does this feature already exist or can I add it somehow, perhaps in user
> land code?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/romaricdrigon/MetaYaml/issues/11#issuecomment-152218912>
> .
>


-- 
Romaric Drigon

**Comment by psynaptic** [comment]
Maybe I can give you an example as I'm struggling to build a schema for my document:

```yaml
keys: # always called "keys"
  my-key: # any arbitrary key name(s)
    secure: # must always be present in this node
      encoded-string # literal string value
variables: # always called "variables"
  global: # one of 2 options
    FOO: foo # any arbitrary key name(s) with literal string value
    BAR: bar
  script: # the other of the 2 options
    foo: foo
    password:
      secure: # if the node is an array, it must have a "secure" element
        encoded-string # literal string value
my-steps: # either "my-steps" or "my_steps"
  - step-1: # arbitrary key name. must be an ordered mapping
      type: script # optionally specified type key. if not specified, defaults to "script"
      script: # only if type is "script" or not present should script key be allowed
        - command1 # must be an ordered mapping of literal string values
        - command2
  - step-2:
      type: make # type may be one of a finite set
      file: project.make # if type is "make", the "file" key is required
  - arbitrary-name:
      script: # same as step-1 but omitting type, since the default is "script"
        - echo foo
        - command2
```

I'm not sure it is even possible to create a MetaYaml schema to describe and validate this, since it is not strict about key names. There are a couple of places where keys are arbitrary but it matters what they contain.

What do you think? Can MetaYaml help with this, or is my document format too loose?
