### ISSUE TITLE
Cannot write even basic schema

### ISSUE THREAD

**Issue by OnkelTem** [romaricdrigon/MetaYaml#19]
I cannot explain why my schema doesn't work, I just continue getting some frustrating error message not explaining anything.

Sample input:
```yaml
database:
  type: sqlite
  params:
    path: "some_path"
```

Schema:

```yaml
root:
  _type: array
  _children:
    database:
      _type: array
      _required: true
      _description: "Database details"
      _children:
        type:
          _required: true
          _type: text
          _description: "Database plugin to use: sqlite, mysql, etc... Check the list of available db plugins."
        params:
          _required: true
          _type: partial
          _description: "Database plugin parameters."
          _partial: sqlite


partials:
  sqlite:
    _type: array
    _required: true
    _children:
      path:
        _type: text
        _required: true
```

And the error message I'm getting:

```
Unable to validate schema with error: The choice node 'node' is invalid with error: The value 'array' is not allowed for node 'node_text._type'
```

So it is saying about `node`. I don't have any **node**. And I don't have any `array`s inside `text`s - just check it out above.
What I do wrong eh?
